### ISSUE TITLE
TREC news dataset's citation question

### ISSUE THREAD

**Issue by nzw0301** [Leooyii/LCEG#2]
Dear authors,

I really enjoy reading the paper (and watching the video too). I might misunderstand the paper but let me ask a question on trec news dataset.

In Sec. 4, the dataset is mentioned as in 

>  We use the Trec News [[Kontonis et al., 2024]](https://arxiv.org/abs/2405.07937) dataset for this task.

I'm not sure how the cited paper is related, because it looks like a theoretical paper accepted at COLT 2024. 

By the way, in Sec. 5, the dataset is mentioned as in 

> We evaluate TREC News [[Li and Roth, 2002]](https://aclanthology.org/C02-1150.pdf).

Best regards,

**Comment by Leooyii** [comment]
Thank you for your careful reading and feedback. The correct citation in Sec. 4 should be:
>We use the Trec News [Kontonis et al., 2024](https://aclanthology.org/C02-1150.pdf) dataset for this task. 

We will correct these typos and update the paper.
Best regards,
