### ISSUE TITLE
How is the perplexity of Figure 4 computed?

### ISSUE THREAD

**Issue by dwzhu-pku** [Leooyii/LCEG#3]
Dear Authors,

Congratulations on this nice work! I also believe that the perplexity of long contexts can indicate performance on downstream tasks, so I feel very fortunate to have come across this paper. However, when I carefully read the relevant descriptions in Section 6, I found some details confusing, particularly the statement: "In Figure 4, we plot the perplexity of models from our evaluated benchmarks against their performance." I would like to understand how exactly the perplexity is calculated for this part. I would greatly appreciate it if you could provide more detailed information. If this was mentioned earlier in the text and I missed it, please forgive me and kindly point it out.

Additionally, I noticed that in Section 4, you mentioned, "Following Press et al. [2022], all perplexity evaluations are calculated using a sliding window with a window size of 256." I humbly suggest replacing window size with a term like stride to avoid confusion, as adopted in the article "EXTENDING CONTEXT WINDOW OF LARGE LANGUAGE MODELS VIA POSITION INTERPOLATION." In fact, the window size should be 2k, 4k, etc., while 256 refers to the number of steps the window slides forward each time.

**Comment by dwzhu-pku** [comment]
@Leooyii

**Comment by Leooyii** [comment]
Thank you for your feedback! Sorry for the late reply.

The perplexity in Figure 4 is evaluated on PG19 at a length of 32k. The specific perplexity values can be found in Table 2 under PG19 32k. We appreciate your careful reading and suggestions, we will replace "window size" with "stride" to avoid confusion.

Best regards,

**Comment by dwzhu-pku** [comment]
Thanks! :-) @Leooyii
